from pathlib import Path
root=Path(__file__).resolve().parent.parent
main=(root/'sprint-helper.js').read_text()
helpers=main[main.index('function parsePoints('):main.index('// Helper: Check if card title')]+main[main.index('function s4tFeatureHelp('):main.index('function renderMembersBurndownModal(')]+main[main.index('function s4tIsCommonCard('):main.index('function s4tIsCommonCardElement(')]
setup='''const NativeDate=Date;window.Date=class extends NativeDate{constructor(...args){super(...(args.length?args:['2026-09-16T12:00:00']))}static now(){return +new NativeDate('2026-09-16T12:00:00')}};
window.errors=[];window.addEventListener('error',e=>errors.push(e.message));localStorage.clear();function getBoardShortLink(){return 'fixture'}function s4tSetSkeleton(){}function s4tRefreshIcon(){return 'R'}
const board={id:'boardid',shortLink:'fixture',name:'Sprint',members:[{id:'a',fullName:'Alex'},{id:'b',fullName:'Blair'}],lists:[{id:'todo',name:'Todo'}],cards:[{id:'commented',name:'Commented yesterday',dateLastActivity:'2026-09-09T10:00:00',due:'2026-09-09T10:00:00',idMembers:['a'],idList:'todo',labels:[]},{id:'current',name:'Current task',dateLastActivity:'2026-09-16T10:00:00',due:'2026-09-30T10:00:00',idMembers:['a'],idList:'todo',labels:[]},{id:'previous',name:'Previous task',dateLastActivity:'2026-09-10T10:00:00',idMembers:['a'],idList:'todo',labels:[]}]};
$.ajax=options=>{const d=$.Deferred();setTimeout(()=>d.resolve(options.url.endsWith('/actions')?[{id:'comment',date:'2026-09-15T10:00:00',data:{card:{id:'commented'}}}]:options.url==='/1/members/me'?{id:'a'}:options.url.includes('/members/me/boards')?[]:board),5);return d.promise()};
'''
tests='''const el=s=>document.querySelector(s),wait=ms=>new Promise(r=>setTimeout(r,ms)),check=(v,m)=>{if(!v)errors.push(m)};(async()=>{try{
const week=s4tEowWeek();localStorage.setItem('s4t-eow-v1:fixture:a:'+week.iso,JSON.stringify({heading:'EOW Update',dateRange:week.label,mode:'both',excluded:[],categories:[{name:'RELEASE TASKS',cards:[]}],manual:false,userEdited:false}));
s4tOpenEow();await wait(60);check(el('[data-eow-week]').value==='2026-09-14','correct current week');check(el('[data-eow-preview]').value.includes('Current task')&&!el('[data-eow-preview]').value.includes('Previous task'),'current-week draft rebuilt');check(el('[data-eow-preview]').value.includes('Commented yesterday'),'yesterday comment includes card with stale last activity');
const input=el('[data-eow-week]');input.value='2026-09-07';input.dispatchEvent(new Event('change'));check(el('[data-eow-preview]').value.includes('Previous task')&&!el('[data-eow-preview]').value.includes('Current task'),'previous-week matching');input.value='2026-09-14';input.dispatchEvent(new Event('change'));check(el('[data-eow-preview]').value.includes('Current task'),'switch back to current');
const mode=el('[data-eow-mode]');mode.value='none';mode.dispatchEvent(new Event('change'));board.cards.push({...board.cards.find(c=>c.id==='current'),id:'new',name:'New current work'});el('[data-eow-refresh]').click();await wait(60);check(el('[data-eow-preview]').value.includes('New current work'),'refresh includes new activity after format change');
const preview=el('[data-eow-preview]');preview.value='My manual report';preview.dispatchEvent(new Event('input'));el('[data-eow-refresh]').click();await wait(60);check(preview.value==='My manual report','manual edits preserved');
}catch(e){errors.push(e.stack)}el('#result').textContent=errors.length?'FAIL: '+errors.join('; '):'PASS: current and previous week switching, automatic draft refresh, new cards and manual draft preservation';})();'''
Path('/tmp/s4t-eow-week-switch.html').write_text('<!doctype html><html><body><pre id="result">RUNNING</pre><script>'+(root/'jquery-2.1.4.min.js').read_text()+'</script><script>'+setup+helpers+(root/'eow-update.js').read_text()+tests+'</script></body></html>')
