from pathlib import Path
root=Path(__file__).resolve().parent.parent
main=(root/'sprint-helper.js').read_text()
parser=main[main.index('function parsePoints('):main.index('// Helper: Check if card title')]
test=r'''const field=document.querySelector('textarea'),errors=[];function check(ok,msg){if(!ok)errors.push(msg)}function input(v){field.value=v;field.dispatchEvent(new Event('input',{bubbles:true}))}function leave(){document.querySelector('button').focus()}
check(field.value==='Original title','view untouched');check(document.querySelector('#s4t-title-point-highlight').textContent.trim()==='() Original title []','brackets inline by default');check(!document.querySelector('.s4t-title-point-shortcuts'),'no separate points row');field.focus();check(field.value==='() Original title []','empty slots');check(document.querySelectorAll('#s4t-title-point-highlight span').length===2,'both brackets highlighted');leave();check(field.value==='Original title','focus alone does not save slots');field.dataset.testid='card-back-title-input';
field.focus();input('(5) Original title [2]');leave();check(field.value==='(5) Original title [2]','points retained on save');
field.focus();input('(8) Changed []');field.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));check(field.value==='(5) Original title [2]','cancel restores original');leave();
field.focus();input('() Updated [3]');field.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));check(field.value==='Updated [3]','enter removes empty assigned slot');leave();
field.value='(4)Title[2]';field.focus();check(field.value==='(4) Title [2]','spaces around title');leave();check(field.value==='(4)Title[2]','unchanged edit preserves original view');
field.value='Title';field.focus();input('() Updated []');leave();check(field.value==='Updated','both empty slots removed');
check(s4tTitlePointSlots('(0) Zero [0]',true)==='(0) Zero [0]','zero points');check(s4tTitlePointSlots('(2/5) Work',true)==='(5) Work [2]','slash points preserved');check(s4tTitlePointSlots('Work (UI) [Team]',true)==='() Work (UI) [Team] []','nonpoint brackets preserved');
let observed;field.addEventListener('input',()=>observed=field.value);s4tSetTitleValue(field,'(9) Work [3]');check(observed==='(9) Work [3]','native setter dispatches input');
leave();field.addEventListener('focus',()=>{field.value='React title'},{once:true});field.value='React title';field.focus();await new Promise(r=>setTimeout(r,20));check(field.value==='() React title []','React focus initialization repaired');leave();await new Promise(r=>setTimeout(r,20));const marks=document.querySelectorAll('#s4t-title-point-highlight span');marks[marks.length-1].dispatchEvent(new MouseEvent('mousedown',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,20));check(document.activeElement===field,'shortcut opens title editor');check(field.selectionStart===field.value.length-1 && field.selectionEnd===field.selectionStart,'completed shortcut places caret inside brackets');leave();check(field.value==='React title','shortcut does not save placeholders');document.querySelector('#result').textContent=errors.length?'FAIL: '+errors.join('; '):'PASS: edit slots, spacing, save, cancel, empty cleanup, existing points and input events';'''
Path('/tmp/s4t-title-points-ui.html').write_text('<html><body><textarea data-testid="card-back-title">Original title</textarea><button>Save</button><pre id="result"></pre><script>'+parser+(root/'title-points-editor.js').read_text()+'setTimeout(async function(){'+test+'},100);</script></body></html>')
