from pathlib import Path
import json
root=Path(__file__).resolve().parent.parent
setup='var requests=0;window.chrome={runtime:{getURL:p=>p}};window.fetch=async()=>{requests++;return {ok:true,text:async()=>'+json.dumps((root/'WORKFLOW-RULES.md').read_text())+'}};localStorage.clear();'
test='''(async()=>{const wait=ms=>new Promise(r=>setTimeout(r,ms)),check=(v,m)=>{if(!v)throw Error(m)};try{
await wait(200);const feedback=document.querySelector('#feedback');check(feedback.previousElementSibling.id==='s4t-workflow-launch','button before feedback');document.querySelector('#s4t-workflow-launch').click();await wait(20);let modal=document.querySelector('#s4t-workflow-rules');check(modal.open,'popup opens');check(modal.textContent.includes('Sprint Helper · Workflow rules'),'extension name shown');check(modal.querySelectorAll('table').length===4,'rules tables rendered');check(modal.textContent.includes('Dheeraj Not Sure'),'examples loaded');s4tWorkflowRules.open();check(document.querySelectorAll('#s4t-workflow-rules').length===1,'one shared popup');modal.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));check(!document.querySelector('#s4t-workflow-rules'),'escape closes');
s4tPreferences.open();document.querySelector('#s4t-preferences-rules').click();await wait(20);modal=document.querySelector('#s4t-workflow-rules');check(modal.open,'settings opens same dialog');check(requests===1,'document cached');modal.querySelector('button').click();check(document.activeElement.id==='s4t-preferences-rules','focus returns to settings');document.querySelector('#s4t-preferences-dialog header button').click();document.querySelector('header').innerHTML='<button id="feedback" aria-label="Share your thoughts">Feedback</button>';await wait(250);check(document.querySelector('#feedback').previousElementSibling.id==='s4t-workflow-launch','header remount restores placement');check(document.querySelectorAll('#s4t-workflow-launch').length===1,'no duplicate launch button');check(!!document.querySelector('#s4t-workflow-launch .s4t-rules-spark'),'colored sparkle icon');document.querySelector('header').innerHTML='<button data-testid="header-member-menu-button">Profile</button>';await wait(250);check(!!document.querySelector('#s4t-workflow-launch'),'header fallback when feedback unlabelled');const late=document.createElement('button');late.setAttribute('aria-label','Share your thoughts about Trello');document.querySelector('header').appendChild(late);await wait(250);check(late.previousElementSibling.id==='s4t-workflow-launch','moves before late feedback');document.querySelector('header').innerHTML='<div id="actions" style="display:flex;flex-direction:row-reverse"><div id="feedback-wrap" style="position:relative"><button aria-label="Share your thoughts">Feedback</button><span class="native-unread" style="position:absolute;right:0;top:0">1</span></div><button>Other</button></div>';await wait(250);const wrap=document.querySelector('#feedback-wrap'),launch=document.querySelector('#s4t-workflow-launch');check(launch.parentElement.id==='actions','mounts outside feedback wrapper');check(!launch.contains(document.querySelector('.native-unread'))&&document.querySelector('.native-unread').parentElement===wrap,'native unread badge stays with feedback');check(!launch.textContent.includes('1'),'help has no unread badge');check(launch.getBoundingClientRect().right<=wrap.getBoundingClientRect().left+1,'visually before feedback in reversed header');launch.click();await wait(20);modal=document.querySelector('#s4t-workflow-rules');check(modal.getBoundingClientRect().width>950,'wider popup');check(modal.querySelector('th').getBoundingClientRect().width>=145,'first column has room');check(modal.textContent.includes('Members Burndown')&&modal.textContent.includes('List-top points'),'feature-specific guidance');modal.querySelector('button').click();
document.querySelector('header').innerHTML='<div id="notification-container" style="position:relative;width:32px"><button data-testid="header-notifications-button" aria-label="1 Notification" style="position:absolute;right:0;top:0;width:32px;height:32px">1</button><button hidden>Menu</button></div>';await wait(250);
const notification=document.querySelector('[data-testid="header-notifications-button"]'),help=document.querySelector('#s4t-workflow-launch');check(help.parentElement===document.querySelector('header'),'fallback outside notification container');check(notification.parentElement.id==='notification-container'&&notification.getAttribute('aria-label')==='1 Notification','native notification unchanged');const hr=help.getBoundingClientRect(),nr=notification.getBoundingClientRect();check(hr.right<=nr.left||hr.left>=nr.right||hr.bottom<=nr.top||hr.top>=nr.bottom,'notification does not overlap help');
document.querySelector('header').innerHTML='<div id="real-header-actions" style="display:flex;align-items:center;gap:8px"><button id="real-feedback" aria-label="Feedback" aria-owns="feedback-menu-popover-content" aria-expanded="false" style="width:32px;height:32px">Megaphone</button><button data-testid="header-notifications-button" aria-label="1 Notification" style="width:32px;height:32px">1</button><button>Help</button><button>Profile</button></div>';await wait(250);const realFeedback=document.querySelector('#real-feedback'),realHelp=document.querySelector('#s4t-workflow-launch'),realNotification=document.querySelector('[data-testid="header-notifications-button"]');check(realHelp.nextElementSibling===realFeedback,'actual Trello Feedback attributes anchor correctly');check(realHelp.getBoundingClientRect().right<=realFeedback.getBoundingClientRect().left,'own space before megaphone');check(realHelp.getBoundingClientRect().right<=realNotification.getBoundingClientRect().left,'no notification overlap');
document.querySelector('#result').textContent='PASS: both entries, shared document, keyboard close, focus return, cached load, header remount';
}catch(e){document.querySelector('#result').textContent='FAIL: '+e.stack}})();'''
Path('/tmp/s4t-workflow-rules-ui.html').write_text('<html><head><style>'+(root/'sprint-helper.css').read_text()+'</style></head><body><header id="header"><button id="feedback" data-testid="header-feedback-button"><svg></svg></button></header><pre id="result">RUNNING</pre><script>'+setup+(root/'feature-preferences.js').read_text()+(root/'workflow-rules.js').read_text()+test+'</script></body></html>')
