from pathlib import Path
root=Path(__file__).resolve().parent.parent;s=(root/'sprint-helper.js').read_text()
helpers=s[s.index('function parsePoints('):s.index('// Helper: Check if card title')]+s[s.index('function renderMembersHtml('):s.index('function showBurndown()')]
attention=s[s.index('/* Attention filters use their own class'):s.index('/* Cards List:')]
setup='''window.fixtureErrors=[];window.addEventListener('error',e=>fixtureErrors.push(e.message));localStorage.clear();
var S4T_CARD_SEL='[data-testid="list-card"]',S4T_LIST_SEL='[data-testid="list"]',S4T_TITLE_SEL='[data-testid="card-name"]';
function getBoardShortLink(){return 'fixture';}function updateBurndownLink(){}function calcListPoints(){}function showSettings(){}function hideMembersBurndown(){$('#s4t-modal-overlay').remove();}function updateModalContent(){}function readAllCardsSynchronously(){}
window.boardData={name:'Sprint 42',cards:[{name:'Task',desc:'Scope',shortLink:'abc',idList:'todo',idMembers:['member'],idLabels:['feature'],idChecklists:[]}],lists:[{id:'todo',name:'Todo',closed:false}],checklists:[],members:[{id:'member',fullName:'Alex'}],labels:[{id:'hotfix',name:'Hotfix',color:'red'},{id:'feature',name:'Feature',color:'green'}]};
var pending=[];$.ajax=function(){var d=$.Deferred();pending.push(d);return d.promise();};
'''
tests='''setTimeout(async()=>{const check=(v,m)=>{if(!v)fixtureErrors.push(m)},wait=()=>new Promise(r=>setTimeout(r,300));try{
document.getElementById('s4t-attention-button').click();pending.shift().resolve(boardData);await wait();
const panel=document.getElementById('s4t-attention-panel'),all=panel.querySelector('[data-attention-all-labels]'),labels=()=>Array.from(panel.querySelectorAll('[data-attention-label]'));
check(all.checked&&labels().every(x=>x.checked),'all labels checked by default');all.click();check(labels().every(x=>!x.checked),'all labels off');all.click();check(labels().every(x=>x.checked),'all labels restored');
panel.querySelector('[data-attention-label="feature"]').click();check(all.indeterminate&&!all.checked,'partial state');panel.querySelector('[data-attention-label="feature"]').click();check(all.checked,'individual labels sync all');
panel.querySelector('[data-check="hotfix"]').click();check(panel.querySelector('[data-attention-label="hotfix"]').checked&&!panel.querySelector('[data-attention-label="feature"]').checked,'hotfix linked');all.click();check(all.checked&&labels().every(x=>x.checked),'all labels works with hotfix');
const refresh=panel.querySelector('[data-refresh]'),column=panel.querySelector('.s4t-attention-labels'),row=labels()[0],before=column.getBoundingClientRect(),buttonBefore=refresh.getBoundingClientRect();refresh.click();
check(refresh.classList.contains('s4t-refreshing'),'refresh spinner active');check(column.getBoundingClientRect().top===before.top,'refresh does not shift columns');check(refresh.getBoundingClientRect().width===buttonBefore.width,'refresh icon fixed width');pending.shift().resolve(boardData);await wait();check(labels()[0]===row,'unchanged choices retain DOM');check(!refresh.classList.contains('s4t-refreshing'),'spinner stops');
const active=document.getElementById('s4t-attention-button');check(getComputedStyle(active).backgroundColor==='rgba(0, 0, 0, 0)','active attention has transparent inner button');
panel.querySelector('[aria-label="Close attention panel"]').click();
renderMembersBurndownModal({boardName:'Sprint 42',team:{assigned:20,completed:8,remaining:12,cardsTotal:7,cardsCompleted:3,completionPercentage:40},members:[{name:'Alex',initials:'AX',cardsTotal:7,cardsCompleted:3,cardsPending:4,assigned:20,completed:8,remaining:12,completionPercentage:40}]});
check(!document.getElementById('s4t-settings-action'),'no Settings button');check(document.getElementById('s4t-sum-cards').textContent==='3 / 7','completed and total cards');check(document.getElementById('s4t-sum-card-rate').textContent==='42.86% completion rate','card completion rate');check(document.getElementById('s4t-sum-completed').textContent==='8 hrs','completed hours');check(!document.getElementById('s4t-theme-toggle'),'burndown follows native theme');check(getComputedStyle(document.getElementById('s4t-members-modal')).backgroundColor==='rgb(34, 34, 34)','burndown native dark surface');
}catch(e){fixtureErrors.push(e.message)}document.getElementById('result').textContent=fixtureErrors.length?'FAIL: '+fixtureErrors.join('; '):'PASS: all labels, partial states, hotfix sync, stable refresh, DOM retention, active icon, native burndown theme';},200);'''
html='''<!doctype html><html style="--ds-surface-overlay:#222;--ds-text:#eee;--ds-text-subtle:#aaa;--ds-border:#444;--ds-background-neutral:#333;--dynamic-text-color:#eee"><head><meta charset="utf-8"><style>body{background:#191919;font:14px system-ui;color:#eee}#result{position:fixed;bottom:0;z-index:20000;background:#fff;color:#111;white-space:pre-wrap}</style><style>'''+(root/'sprint-helper.css').read_text()+'''</style></head><body><div id="s4t-board-tools"><button id="membersBurndownLink">Members</button></div><pre id="result">RUNNING</pre><script>'''+(root/'jquery-2.1.4.min.js').read_text()+'</script><script>'+setup+helpers+attention+'</script><script>'+tests+'</script></body></html>'
Path('/tmp/s4t-panel-ui.html').write_text(html)
