from pathlib import Path
root=Path(__file__).resolve().parent.parent
s=(root/'sprint-helper.js').read_text()
helpers=s[s.index('function parsePoints('):s.index('// Helper: Check if card title')]+s[s.index('function s4tSetSkeleton('):s.index('function s4tLoadMembers(')]+s[s.index('function renderMembersHtml('):s.index('function showBurndown(')]+s[s.index('function updateBurndownLink('):s.index('var cachedBoardData')]
setup='''var errors=[];window.addEventListener('error',e=>errors.push(e.message));localStorage.clear();window.confirm=()=>true;
var pending=[];$.ajax=(options)=>{var d=$.Deferred();if(options.url==='/1/members/me')d.resolve({id:'a'});else if(options.url==='/1/members/me/boards')d.resolve([{id:'fixture',shortLink:'fixture',name:'23sep2026release',idOrganization:'workspace'},{id:'previous',shortLink:'previous',name:'09sep2026release',idOrganization:'workspace'}]);else pending.push(d);return d.promise()};
function getBoardShortLink(){return 'fixture'}function s4tIsCommonCard(card){return /^(Release|Template card)$/i.test(card.name)}function s4tBoardToolbarAnchor(){return document.getElementById('native-filter')}
function hideMembersBurndown(){$('#s4t-modal-overlay').remove()}function showMembersBurndown(){}function s4tLoadMembers(){}
var data={id:'fixture',shortLink:'fixture',name:'23sep2026release',idOrganization:'workspace',members:[{id:'b',fullName:'Sam'},{id:'a',fullName:'Alex'}],lists:[{id:'todo',name:'Todo'},{id:'done',name:'Done'}],cards:[{id:'card1',name:'(3) Improve search',idList:'todo',idMembers:['a'],labels:[{name:'Client Requests'}],dateLastActivity:new Date().toISOString()},{id:'card2',name:'(1) Patch login',idList:'done',idMembers:['a'],labels:[{name:'Hotfix'}],dateLastActivity:new Date().toISOString()}]};
'''
tests='''setTimeout(async()=>{const check=(value,msg)=>{if(!value)errors.push(msg)},el=s=>document.querySelector(s),wait=()=>new Promise(r=>setTimeout(r,30));try{
updateBurndownLink();updateBurndownLink();check(document.querySelectorAll('#s4t-eow-launch').length===1,'one stable EOW icon');el('#s4t-eow-launch').click();check(el('.s4t-eow-content').classList.contains('s4t-loading-surface'),'opening skeleton');check(el('.s4t-panel-skeleton').getBoundingClientRect().height>100,'EOW skeleton has height');check(getComputedStyle(el('.s4t-panel-skeleton')).visibility==='visible','EOW skeleton visible');pending.shift().resolve(data);await wait();
check(!el('.s4t-eow-content').hasAttribute('inert'),'content enabled');check(el('[data-eow-member]').value==='a','signed-in member selected over first member');check(!!el('header [data-eow-sources]'),'board name in header');check(!el('.s4t-eow-content [data-eow-sources]'),'board name not duplicated in body');check(el('[data-eow-week]').type==='hidden','only one visible date field');check(!!el('.s4t-eow-date-field svg'),'calendar icon inside date field');check(!el('header [data-eow-week]'),'no date picker in header');check(!!el('.s4t-eow-preview-pane [data-eow-copy] svg'),'icon-only copy in preview');check(el('[data-eow-preview]').value.includes('Improve search'),'generated preview');check(el('[data-eow-preview]').value.includes('HOTFIX - [1]'),'hotfix category');
check(!el('[aria-label="Rebuild preview from categories"]'),'no rebuild button');check(el('.s4t-eow-preview-pane [data-eow-mode]'),'points selector in preview');check(!el('.s4t-eow-task select'),'no repeated category selectors');check(!el('[aria-label="Move task up"]'),'no task arrows');check(el('[data-eow-add-category]').getBoundingClientRect().bottom<el('#s4t-eow-dialog').getBoundingClientRect().bottom,'add category visible');
const excludeMenu=el('.s4t-eow-exclude');excludeMenu.dispatchEvent(new MouseEvent('mouseover',{bubbles:true}));check(!el('[data-eow-lists]').hidden,'hover opens lists');excludeMenu.dispatchEvent(new MouseEvent('mouseout',{bubbles:true,relatedTarget:document.body}));await new Promise(r=>setTimeout(r,300));check(el('[data-eow-lists]').hidden,'hover leave closes lists');
const source=el('[data-category-index="2"] .s4t-eow-drag'),target=el('[data-category-index="1"]');const transfer=new DataTransfer();source.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:transfer}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));check(document.querySelectorAll('[data-category-index="1"] .s4t-eow-task').length===2,'drag moves task across categories');
el('[data-eow-add-category]').click();check(document.querySelectorAll('.s4t-eow-category').length===6,'add category works');
const mode=el('[data-eow-mode]');mode.dispatchEvent(new MouseEvent('mouseover',{bubbles:true}));check(!!el('.s4t-hover-selector'),'points hover opens');el('.s4t-hover-selector button').click();check(!el('.s4t-hover-selector'),'selection closes');
el('[data-eow-date-range]').dispatchEvent(new MouseEvent('mouseover',{bubbles:true}));check(!!el('.s4t-hover-calendar-grid'),'date hover calendar');check(document.querySelectorAll('.s4t-week-selected').length===7,'whole selected week highlighted');el('[data-eow-date-range]').dispatchEvent(new MouseEvent('mousedown',{bubbles:true}));check(!!el('.s4t-hover-calendar-grid'),'date click keeps calendar open');document.querySelectorAll('.s4t-week-selected')[2].click();el('[data-eow-date-range]').dispatchEvent(new MouseEvent('mouseover',{bubbles:true}));check(document.querySelectorAll('.s4t-week-selected').length===7,'chosen day selects whole week');document.body.dispatchEvent(new MouseEvent('mousedown',{bubbles:true}));check(!el('.s4t-hover-selector'),'outside mousedown closes');
el('[data-eow-member]').dispatchEvent(new MouseEvent('mouseover',{bubbles:true}));check(!!el('.s4t-hover-selector'),'member hover opens');document.body.dispatchEvent(new MouseEvent('mousedown',{bubbles:true}));
const preview=el('[data-eow-preview]');preview.value='My edited weekly update';preview.dispatchEvent(new Event('input',{bubbles:true}));el('[data-eow-refresh]').click();check(el('.s4t-eow-content').classList.contains('s4t-loading-surface'),'refresh skeleton');pending.shift().resolve(data);check(el('[data-eow-preview]').value==='My edited weekly update','refresh preserves preview');
el('[aria-label="Close EOW Update"]').click();el('#s4t-eow-launch').click();pending.shift().resolve(data);check(el('[data-eow-preview]').value==='My edited weekly update','reopen restores draft');
const member=el('[data-eow-member]');member.value='b';member.dispatchEvent(new Event('change'));check(!el('[data-eow-preview]').value.includes('Improve search'),'member isolated');check(!el('[data-eow-lists] input'),'no other member lists');member.value='a';member.dispatchEvent(new Event('change'));check(el('[data-eow-preview]').value==='My edited weekly update','member draft restored');
el('[data-eow-reset]').click();check(el('[data-eow-preview]').value.includes('Improve search'),'reset rebuilds');
check(el('[data-eow-mode]').previousElementSibling===el('.s4t-eow-exclude'),'exclude before points');check(Math.abs(el('[data-eow-categories]').getBoundingClientRect().height-el('[data-eow-preview]').getBoundingClientRect().height)<2,'left and right content same height');const exclude=el('[data-eow-lists] input');window.confirm=()=>{throw new Error('Unexpected exclusion alert')};exclude.click();window.confirm=()=>true;check(!el('[data-eow-preview]').value.includes('Improve search'),'list exclusion');check(el('[data-eow-preview]').value.includes('Patch login'),'other list retained');
el('[data-eow-refresh]').click();pending.shift().reject();check(!el('.s4t-eow-content').classList.contains('s4t-loading-surface'),'failure clears skeleton');check(el('.s4t-eow-status').textContent.includes('Could not load'),'clean error');
el('[aria-label="Close EOW Update"]').click();el('#s4t-eow-launch').click();const stale=pending.shift();el('[aria-label="Close EOW Update"]').click();el('#s4t-eow-launch').click();stale.resolve(data);check(el('.s4t-eow-content').classList.contains('s4t-loading-surface'),'stale response ignored');pending.shift().resolve(data);el('[aria-label="Close EOW Update"]').click();
el('#s4t-eow-launch').click();pending.shift().resolve(data);check(!el('[data-eow-boards]'),'no manual board selector');check(el('[data-eow-release-warning]').textContent.includes('Date range includes'),'automatic overlap warning');check(pending.length===0,'previous cards not fetched until clicked');
check(el('[data-eow-release-warning]').textContent.includes('Add those tasks manually'),'manual previous-release notice');check(!el('[aria-label="Select previous release cards"]'),'no previous-card picker');check(pending.length===0,'no previous cards fetched');el('[aria-label="Close EOW Update"]').click();
const members=Array.from({length:30},(_,i)=>({name:'Member '+i,initials:'MM',cardsTotal:2,cardsCompleted:1,cardsPending:1,assigned:8,completed:3,remaining:5,completionPercentage:38}));renderMembersBurndownModal({boardName:'Sprint',team:{assigned:240,completed:90,remaining:150,cardsTotal:60,cardsCompleted:30},members});
const summary=el('#s4t-team-summary'),list=el('#s4t-members-container'),top=summary.getBoundingClientRect().top;list.scrollTop=500;await wait();check(list.scrollTop>0,'member list scrolls');check(summary.getBoundingClientRect().top===top,'summary fixed');check(getComputedStyle(el('.s4t-modal-body')).overflowY==='hidden','no parent scrolling');check(parseInt(getComputedStyle(list).paddingBottom)>=24,'bottom breathing room');hideMembersBurndown();el('#s4t-eow-launch').click();pending.shift().resolve(data);
}catch(error){errors.push(error.stack)}el('#result').textContent=errors.length?'FAIL: '+errors.join('; '):'PASS: toolbar, skeletons, categories, drafts, exclusions, refresh failure, stale response, fixed summary and bottom spacing';},100);
'''
html='<!doctype html><html><head><meta charset="utf-8"><style>body{font:14px system-ui}#result{position:fixed;bottom:0;background:white;color:black;z-index:20000;white-space:pre-wrap}</style><style>'+(root/'sprint-helper.css').read_text()+'</style></head><body><button id="native-filter">Filters</button><pre id="result">RUNNING</pre><script>'+(root/'jquery-2.1.4.min.js').read_text()+'</script><script>'+setup+helpers+(root/'eow-update.js').read_text()+(root/'hover-selectors.js').read_text()+'</script><script>'+tests+'</script></body></html>'
Path('/tmp/s4t-eow-ui.html').write_text(html)
